CREATE DATABASE IF NOT EXISTS metronomo_online
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

USE metronomo_online;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS configuraciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario_id INT NOT NULL,
    bpm INT NOT NULL DEFAULT 100,
    compas INT NOT NULL DEFAULT 4,
    sonido VARCHAR(30) NOT NULL DEFAULT 'click',
    acentos TINYINT(1) NOT NULL DEFAULT 1,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
